# Generated by Django 4.0.1 on 2022-01-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_mail_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
